application: edrop
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /run/.*
  script: etl.py
  login: admin
- url: .*
  script: main.py
